name: "Open Source Point of Sale"
description: "Web-based point of sale application written in PHP using CodeIgniter framework with MySQL database and Bootstrap 3 UI."
techstacks:
  - name: PHP
    iconUrl: "https://cdn.simpleicons.org/php"
  - name: MySQL
    iconUrl: "https://cdn.simpleicons.org/mysql"
  - name: CodeIgniter
    iconUrl: "https://cdn.simpleicons.org/codeigniter"
  - name: Bootstrap
    iconUrl: "https://cdn.simpleicons.org/bootstrap"
iconUrl: "https://ui-avatars.com/api/?name=POS+System"
sharedVariable:
  ENVIRONMENT: "production"
  TIMEZONE: "UTC"

services:
  pos-system:
    type: application
    order: 1
    serviceUrl: "https://github.com/opensourcepos/opensourcepos.git"
    iconUrl: "https://avatars.githubusercontent.com/u/31845758?s=48&v=4"
    ports:
      - "80:80"
    buildConfig:
      packages:
        - "php8.1"
        - "apache2"
        - "mysql-client"
      installCommand: "composer install --no-dev --optimize-autoloader"
      startCommand: "apache2-foreground"
      ports:
        - "80:80"
      environment:
        - ENVIRONMENT=production
        - TIMEZONE=UTC
        - DB_HOST=${host_mysql}
        - DB_DATABASE=${env_mysql_MYSQL_DATABASE}
        - DB_USERNAME=${env_mysql_MYSQL_USER}
        - DB_PASSWORD=${env_mysql_MYSQL_PASSWORD}
      volumes:
        - "pos-data:/var/www/html"

  mysql:
    type: database
    order: 2
    serviceUrl: "mysql:8.0"
    iconUrl: "https://cdn.simpleicons.org/mysql"
    image: mysql:8.0
    ports:
      - "3306:3306"
    buildConfig:
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=opensourcepos
        - MYSQL_USER=opensourcepos
        - MYSQL_PASSWORD=password
      volumes:
        - "mysql-data:/var/lib/mysql"